### ISSUE TITLE
프론트엔드 프로젝트 진행 큰그림

### ISSUE THREAD

**Issue by geoseong** [awskrug/kendra-button#3]
안녕하세요

kendra-button의 frontend side 진행 시 같이 익혀 나가야 할 사항들을 여기에 한 번 정리 해 보고 하나씩 지워나가면 어떨까 합니다.

아래 정리 된 내용들은 상단 Project 탭의 [Frontend Project](https://github.com/awskrug/kendra-button/projects/1)에다가 항목별로 TODO로 올려 놓았습니다

다른 의견 있으면 남겨주시기 바랍니다.

## Boilerplate
[**next.js**](https://nextjs.org)
react framework 로써 static generation, server side rendering, page routing, typescript, css-in-js 내장지원

**참고자료**
- [next.js "Learn" 페이지](https://nextjs.org/learn/basics/create-nextjs-app)
- [typescript 프로젝트 기본예제: next-learn-starter](https://github.com/zeit/next-learn-starter/tree/master/typescript-final)

[**Amplify CLI & Framework**](https://docs.amplify.aws/)
AWS 주요 리소스들(API Gateway, Lambda, Cognito, AppSync, S3, etc...)을 CLI로 직접 만들고, Framework에서 사용 가능
CI/CD, Web Hosting 또한 가능함

**TODO**
- [x] external api 호출 방법 정하기
  - [git project link](https://github.com/awskrug/kendra-button/projects/1#card-38782204)
  - [`Amplify의 API` 사용(GraphQL or REST)](https://docs.amplify.aws/lib/restapi/fetch/q/platform/js)
    - 이미 존재하는 endpoint도 configure 하여 호출 가능
  - [`node-fetch` 사용](https://github.com/node-fetch/node-fetch)
    - next.js의 [learn페이지의 예제(Pre-rendering and Data Fetching -> 8번째 페이지)](https://nextjs.org/learn/basics/data-fetching/getstaticprops-details)로 사용되고 있고, light한 라이브러리

## End User Use Case
**TODO**
- [x] 우리 서비스를 넣고자 하는 사용자 사이트 안에 넣는 방법 구상
  - [git project link](https://github.com/awskrug/kendra-button/projects/1#card-38782270)
  - `구상 1`: 사용자 페이지의 <script> 태그 안에 iframe(src에 우리 서비스 링크) 을 담고 unique id를 넣어서 보안기능을 갖춘(브라우저에서 unique id를 갈취하더라도 안전한) js코드 구현

## 관리자 페이지 회원관리
- [Amplify의 Authentication](https://docs.amplify.aws/lib/auth/getting-started/q/platform/js) 사용

**TODO**
  - [x] Amplify CLI로 AWS Cognito User Pool을 생성한 후 Amplify Framework을 통하여 코딩하기
    - [git project link](https://github.com/awskrug/kendra-button/projects/1#card-38782288)
    - [Tutorial: Deploy a GraphQL API with Authentication & Authorization in 8 minutes with AWS Amplify & AWS AppSync](https://www.youtube.com/watch?v=gQf8jIuimlw)
  - [x] AWS Cognito 리소스를 어디에 생성 할 지 정하기
    - [git project link](https://github.com/awskrug/kendra-button/projects/1#card-38782295)

## 웹표준
**TODO**
- [ ] 사이트 홍보 SEO를 위한 HTML5 태그 익히기
  - [git project link](https://github.com/awskrug/kendra-button/projects/1#card-38782382)

## workflow
**TODO**
- [x] 페이지 흐름 구상하기

## git 협업 제안
- **kendra-button** 리포지토리에 frontend/backend 프로젝트가 한번에 들어있으므로, 각 프로젝트 별로 feature branch를 만들어서 작업 후 PR을 통하여 여러 contributor들에게 review를 받은 후, master branch로 통합하는 방식
  - ex) feature-frontend-styling, feature-backend-crawl
  - [참고자료: Git/GitHub branching standards & conventions](https://gist.github.com/digitaljhelms/4287848)
- git commit 중 frontend 내용에 변동이 있으면 감지해서 Amplify CI/CD 툴과 연동하여 자동배포하기
  - [YouTube Tutorial: Hosting & Continuous Deployment for Front Ends and Serverless Back Ends using AWS Amplify](https://www.youtube.com/watch?v=SHBCim7IzG0)

**Comment by hunkim** [comment]
좋은 정보 감사합니다. 저도 열심히 공부하겠습니다.

**Comment by wesky93** [comment]
백엔드에서 api를 apigateway로 제공할경우 Amplify의 API를 쓰시면 인증을 쉽게 붙일수 있어 편하게 작업하실수 있지 않을까 싶습니다!
