### ISSUE TITLE
dev / prod environment 나누기

### ISSUE THREAD

**Issue by geoseong** [awskrug/kendra-button#72]
## 목표
Backend에서 `dev`, `prod`로 나눈 것에 맞춰서 Frontend 도 똑같이 `dev`, `prod`로 나눠서 개발환경을 구성해야 함

### Amplify Environment
- 현재 프론트엔드는 Amplify 프로젝트 이고, `dev` environment로 구현 되어 있으므로 Amplify CLI를 이용해서 `prod` environment를 추가해 나가야 함
  - [x] 추가 완료

### Github Branch
- **dev**: `frontend-dev`
- **prod**: `master`

### Subdomain
Amplify 세팅에서 Git branch와 연결 해 주어야 함
- **frontend-dev**: [`https://dev.kendra.fun`](https://dev.kendra.fun)
- **prod**: [`https://admin.kendra.fun`](https://admin.kendra.fun)

### Backend 호출 endpoint
- **dev**: https://dev.kendra-btns.whatilearened.today/graphql (**noauth**: https://dev.kendra-btns.whatilearened.today/noauth/graphql)
- **prod**: https://prod.kendra-btns.whatilearened.today/graphql (**noauth**: https://prod.kendra-btns.whatilearened.today/noauth/graphql)

### Cognito 리소스 분리
#47 부분 인식하여 
- [x] `dev` / `prod` 환경에 따라 Cognito 리소스 분리
- [x] 기존 데이터의 `Username` 이 UUID인 것을 email주소로 변경 
- Cognito UserPool 백업/복원
  - [x] Cognito userpool data 백업/복원하는 코드 짜기
    - 여유가 안될 때: [`cognito-backup-restore` CLI & module](https://github.com/rahulpsd18/cognito-backup-restore) 이용하여 백업/복원 시도하기
    - #73 에서 작업
  - [x] Cognito `Pre sign-up` Lambda Trigger 코드 백업하기

**Comment by chloe-codes1** [comment]
## Cognito UserPool 백업/복원

Cognito UserPool 의 `backup` / `restore` 는 성공하였으나, 
Social login user에 대한 `restore` 시 아래와 같은 에러를 뱉음.
```
{
"ChallengeName":"NEW_PASSWORD_REQUIRED",
"ChallengeParameters":
    {"requiredAttributes":"[]","userAttributes":" 
    {\"email_verified\":\"false\",\"email\":\"juhyun.kim@lindsey.edu\"}"},
    "Session":"...."
}
```

## TODO

`NEW_PASSWORD_REQUIRED` error에 대한 처리필요
